SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-d75mf61r0fns73f7nd80-a.singapore-postgres.render.com:5432/portfolio_db_d1xs
SPRING_DATASOURCE_USERNAME=portfolio_user
SPRING_DATASOURCE_PASSWORD=SssreaxR7iQvAFmAd5nnqsoV6Csh6VGS
JWT_SECRET=myPortfolioSuperSecretKeyForJWT2024AbcXyz!!