# Server
server.port=8080

# PostgreSQL (Render)
spring.datasource.url=jdbc:postgresql://dpg-d75mf61r0fns73f7nd80-a.singapore-postgres.render.com:5432/portfolio_db_d1xs
spring.datasource.username=portfolio_user
spring.datasource.password=SssreaxR7iQvAFmAd5nnqsoV6Csh6VGS
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=myPortfolioSuperSecretKeyForJWT2024AbcXyz!!
jwt.expiration=86400000